// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcLvgVXEKLQuOEd0oWblvaHRc12tsG4wE',
    appId: '1:802884049696:web:f4f38d963b758b54c8d545',
    messagingSenderId: '802884049696',
    projectId: 'hourstack-app',
    authDomain: 'hourstack-app.firebaseapp.com',
    storageBucket: 'hourstack-app.firebasestorage.app',
    measurementId: 'G-GZCPJXSEWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuMz4VGt-oyIHhYGrUnMmUGVK4suZqU4',
    appId: '1:802884049696:android:31bada678e864252c8d545',
    messagingSenderId: '802884049696',
    projectId: 'hourstack-app',
    storageBucket: 'hourstack-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmzzkQztngImr2tUFWKYsx4hOz0EuiEQI',
    appId: '1:802884049696:ios:d176d69addb33d3ac8d545',
    messagingSenderId: '802884049696',
    projectId: 'hourstack-app',
    storageBucket: 'hourstack-app.firebasestorage.app',
    iosClientId: '802884049696-uosgaptrbcpdrv0tauuiblh0td7t6grv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hourstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmzzkQztngImr2tUFWKYsx4hOz0EuiEQI',
    appId: '1:802884049696:ios:d176d69addb33d3ac8d545',
    messagingSenderId: '802884049696',
    projectId: 'hourstack-app',
    storageBucket: 'hourstack-app.firebasestorage.app',
    iosClientId: '802884049696-uosgaptrbcpdrv0tauuiblh0td7t6grv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hourstack',
  );
}
