import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../data/models/project_model.dart';
import '../../../data/repositories/project_repository.dart';
import '../../../app/utils/constants.dart';
import 'package:image_picker/image_picker.dart';

class ProjectController extends GetxController {
  final ProjectRepository _repository;

  ProjectController({ProjectRepository? repository})
    : _repository = repository ?? Get.find<ProjectRepository>();

  final RxList<ProjectModel> projects = <ProjectModel>[].obs;
  final RxList<String> clients = <String>[].obs;
  final RxBool isLoading = true.obs;
  final Rxn<ProjectModel> selectedProject = Rxn<ProjectModel>();
  final Rxn<XFile> selectedCoverImage = Rxn<XFile>();
  final _picker = ImagePicker();

  void selectProject(ProjectModel? project) {
    selectedProject.value = project;
  }

  @override
  void onInit() {
    super.onInit();
    projects.bindStream(_repository.getProjectsStream());

    // Initialize mock clients if empty
    clients.addAll(['Acme Corp', 'Global Tech', 'Starlight Inc']);

    // Listen for projects changes to sync clients
    ever(projects, (List<ProjectModel> projectList) {
      if (isLoading.value) isLoading.value = false;

      // Update clients list with any new client names found in projects
      for (var project in projectList) {
        if (project.clientName.isNotEmpty &&
            !clients.contains(project.clientName)) {
          clients.add(project.clientName);
        }
      }

      if (projectList.isEmpty) {
        seedMockProjects();
      }
    });
  }

  Future<void> addProject(
    String name,
    String description,
    double hourlyRate, {
    String clientName = '',
    String currency = AppConstants.defaultCurrency,
    double monthlyHours = 0.0,
    double monthlyProgress = 0.0,
    int colorValue = 0xFF6366F1,
    int iconCodePoint = 0xe232,
    double weeklyGoalHours = 0.0,
    String paymentType = 'Hourly',
    double fixedPrice = 0.0,
    double estimatedBudget = 0.0,
    bool isBillable = true,
    bool isBudgetAlertEnabled = false,
    DateTime? deadline,
    String? coverImageUrl,
  }) async {
    final newProject = ProjectModel(
      id: '', // Generated by Firestore
      name: name,
      description: description,
      clientName: clientName,
      hourlyRate: hourlyRate,
      currency: currency,
      createdAt: DateTime.now(),
      isActive: true,
      monthlyHours: monthlyHours,
      monthlyProgress: monthlyProgress,
      colorValue: colorValue,
      iconCodePoint: iconCodePoint,
      weeklyGoalHours: weeklyGoalHours,
      paymentType: paymentType,
      fixedPrice: fixedPrice,
      estimatedBudget: estimatedBudget,
      isBillable: isBillable,
      isBudgetAlertEnabled: isBudgetAlertEnabled,
      deadline: deadline,
      coverImageUrl: coverImageUrl,
    );
    try {
      final projectRef = await _repository.firestore
          .collection('users')
          .doc(_repository.currentUserId)
          .collection('projects')
          .add(newProject.toMap());

      // If image is selected, upload it and update the project
      if (selectedCoverImage.value != null) {
        final url = await _repository.uploadProjectCover(
          selectedCoverImage.value!,
          projectRef.id,
        );
        if (url != null) {
          await projectRef.update({'coverImageUrl': url});
        }
      }

      selectedCoverImage.value = null; // Clear selection
      Get.back();
      Get.snackbar('Success', 'Project created successfully');
    } catch (e) {
      Get.snackbar('Error', 'Failed to create project: $e');
    }
  }

  Future<void> updateProject(
    ProjectModel project, {
    String? name,
    String? description,
    double? hourlyRate,
    String? clientName,
    String? currency,
    String? paymentType,
    double? fixedPrice,
    bool? isBillable,
    DateTime? deadline,
    String? coverImageUrl,
  }) async {
    String? finalImageUrl = coverImageUrl ?? project.coverImageUrl;

    try {
      if (selectedCoverImage.value != null) {
        finalImageUrl = await _repository.uploadProjectCover(
          selectedCoverImage.value!,
          project.id,
        );
      }

      final updatedProject = ProjectModel(
        id: project.id,
        name: name ?? project.name,
        description: description ?? project.description,
        clientName: clientName ?? project.clientName,
        hourlyRate: hourlyRate ?? project.hourlyRate,
        currency: currency ?? project.currency,
        createdAt: project.createdAt,
        isActive: project.isActive,
        monthlyHours: project.monthlyHours,
        monthlyProgress: project.monthlyProgress,
        colorValue: project.colorValue,
        iconCodePoint: project.iconCodePoint,
        paymentType: paymentType ?? project.paymentType,
        fixedPrice: fixedPrice ?? project.fixedPrice,
        estimatedBudget: project.estimatedBudget,
        isBillable: isBillable ?? project.isBillable,
        isBudgetAlertEnabled: project.isBudgetAlertEnabled,
        totalHours: project.totalHours,
        totalRevenue: project.totalRevenue,
        weeklyGoalHours: project.weeklyGoalHours,
        thisWeekHours: project.thisWeekHours,
        lastWeekHours: project.lastWeekHours,
        milestoneProgress: project.milestoneProgress,
        deadline: deadline ?? project.deadline,
        coverImageUrl: finalImageUrl,
      );

      await _repository.updateProject(updatedProject);
      selectedCoverImage.value = null; // Clear selection
      Get.back();
      Get.snackbar('Success', 'Project updated successfully');
    } catch (e) {
      Get.snackbar('Error', 'Failed to update project: $e');
    }
  }

  void addClient(String name) {
    if (name.isNotEmpty && !clients.contains(name)) {
      clients.add(name);
    }
  }

  void seedMockProjects() {
    final mockProjects = [
      ProjectModel(
        id: '1',
        name: 'E-commerce Redesign',
        clientName: 'Acme Corp',
        hourlyRate: 85.0,
        totalHours: 142.5,
        totalRevenue: 12112.50,
        weeklyGoalHours: 45.0,
        thisWeekHours: 38.5,
        lastWeekHours: 32.2,
        milestoneProgress: 0.95,
        monthlyHours: 120.0,
        monthlyProgress: 0.8,
        colorValue: 0xFF3B82F6,
        iconCodePoint: Icons.language_rounded.codePoint,
        createdAt: DateTime.now(),
      ),
      ProjectModel(
        id: '2',
        name: 'Mobile App Dev',
        clientName: 'Global Tech',
        hourlyRate: 110.0,
        totalHours: 95.0,
        totalRevenue: 10450.00,
        weeklyGoalHours: 40.0,
        thisWeekHours: 25.0,
        lastWeekHours: 38.0,
        milestoneProgress: 0.75,
        monthlyHours: 85.0,
        monthlyProgress: 0.65,
        colorValue: 0xFF818CF8,
        iconCodePoint: Icons.smartphone_rounded.codePoint,
        createdAt: DateTime.now(),
      ),
      ProjectModel(
        id: '3',
        name: 'Brand Identity',
        clientName: 'Starlight Inc',
        hourlyRate: 95.0,
        totalHours: 40.0,
        totalRevenue: 3800.00,
        weeklyGoalHours: 20.0,
        thisWeekHours: 12.0,
        lastWeekHours: 15.0,
        milestoneProgress: 0.45,
        monthlyHours: 40.0,
        monthlyProgress: 0.3,
        colorValue: 0xFFF59E0B,
        iconCodePoint: Icons.palette_rounded.codePoint,
        createdAt: DateTime.now(),
      ),
    ];

    for (var p in mockProjects) {
      _repository.addProject(p);
    }
  }

  Future<void> toggleProjectActiveStatus(ProjectModel project) async {
    final updatedProject = ProjectModel(
      id: project.id,
      name: project.name,
      description: project.description,
      clientName: project.clientName,
      hourlyRate: project.hourlyRate,
      currency: project.currency,
      createdAt: project.createdAt,
      isActive: !project.isActive,
      monthlyHours: project.monthlyHours,
      monthlyProgress: project.monthlyProgress,
      colorValue: project.colorValue,
      iconCodePoint: project.iconCodePoint,
      totalHours: project.totalHours,
      totalRevenue: project.totalRevenue,
      weeklyGoalHours: project.weeklyGoalHours,
      thisWeekHours: project.thisWeekHours,
      lastWeekHours: project.lastWeekHours,
      milestoneProgress: project.milestoneProgress,
    );
    try {
      await _repository.updateProject(updatedProject);
    } catch (e) {
      Get.snackbar('Error', 'Failed to update project: $e');
    }
  }

  Future<void> deleteProject(String projectId) async {
    try {
      await _repository.deleteProject(projectId);
      Get.back();
      Get.snackbar('Success', 'Project deleted');
    } catch (e) {
      Get.snackbar('Error', 'Failed to delete project: $e');
    }
  }

  Future<void> pickCoverImage() async {
    final XFile? image = await _picker.pickImage(
      source: ImageSource.gallery,
      imageQuality: 70,
    );
    if (image != null) {
      selectedCoverImage.value = image;
    }
  }
}
