import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../data/models/project_model.dart';
import '../../../data/repositories/project_repository.dart';
import '../../../app/utils/constants.dart';

class ProjectController extends GetxController {
  final ProjectRepository _repository;

  ProjectController({ProjectRepository? repository})
    : _repository = repository ?? ProjectRepository();

  final RxList<ProjectModel> projects = <ProjectModel>[].obs;
  final RxBool isLoading = true.obs;
  final Rxn<ProjectModel> selectedProject = Rxn<ProjectModel>();

  void selectProject(ProjectModel? project) {
    selectedProject.value = project;
  }

  @override
  void onInit() {
    super.onInit();
    projects.bindStream(_repository.getProjectsStream());

    // Listen for completion of initial load
    ever(projects, (_) {
      if (isLoading.value) isLoading.value = false;
      if (projects.isEmpty) {
        seedMockProjects();
      }
    });
  }

  Future<void> addProject(
    String name,
    String description,
    double hourlyRate, {
    String clientName = '',
    String currency = AppConstants.defaultCurrency,
    double monthlyHours = 0.0,
    double monthlyProgress = 0.0,
    int colorValue = 0xFF6366F1,
    int iconCodePoint = 0xe232,
    double weeklyGoalHours = 0.0,
    String paymentType = 'Hourly',
    double fixedPrice = 0.0,
    double estimatedBudget = 0.0,
    bool isBillable = true,
    bool isBudgetAlertEnabled = false,
  }) async {
    final newProject = ProjectModel(
      id: '', // Generated by Firestore
      name: name,
      description: description,
      clientName: clientName,
      hourlyRate: hourlyRate,
      currency: currency,
      createdAt: DateTime.now(),
      isActive: true,
      monthlyHours: monthlyHours,
      monthlyProgress: monthlyProgress,
      colorValue: colorValue,
      iconCodePoint: iconCodePoint,
      weeklyGoalHours: weeklyGoalHours,
      paymentType: paymentType,
      fixedPrice: fixedPrice,
      estimatedBudget: estimatedBudget,
      isBillable: isBillable,
      isBudgetAlertEnabled: isBudgetAlertEnabled,
    );
    try {
      await _repository.addProject(newProject);
      Get.back();
      Get.snackbar('Success', 'Project created successfully');
    } catch (e) {
      Get.snackbar('Error', 'Failed to create project: $e');
    }
  }

  void seedMockProjects() {
    final mockProjects = [
      ProjectModel(
        id: '1',
        name: 'E-commerce Redesign',
        clientName: 'Acme Corp',
        hourlyRate: 85.0,
        totalHours: 142.5,
        totalRevenue: 12112.50,
        weeklyGoalHours: 45.0,
        thisWeekHours: 38.5,
        lastWeekHours: 32.2,
        milestoneProgress: 0.95,
        monthlyHours: 120.0,
        monthlyProgress: 0.8,
        colorValue: 0xFF3B82F6,
        iconCodePoint: Icons.language_rounded.codePoint,
        createdAt: DateTime.now(),
      ),
      ProjectModel(
        id: '2',
        name: 'Mobile App Dev',
        clientName: 'Global Tech',
        hourlyRate: 110.0,
        totalHours: 95.0,
        totalRevenue: 10450.00,
        weeklyGoalHours: 40.0,
        thisWeekHours: 25.0,
        lastWeekHours: 38.0,
        milestoneProgress: 0.75,
        monthlyHours: 85.0,
        monthlyProgress: 0.65,
        colorValue: 0xFF818CF8,
        iconCodePoint: Icons.smartphone_rounded.codePoint,
        createdAt: DateTime.now(),
      ),
      ProjectModel(
        id: '3',
        name: 'Brand Identity',
        clientName: 'Starlight Inc',
        hourlyRate: 95.0,
        totalHours: 40.0,
        totalRevenue: 3800.00,
        weeklyGoalHours: 20.0,
        thisWeekHours: 12.0,
        lastWeekHours: 15.0,
        milestoneProgress: 0.45,
        monthlyHours: 40.0,
        monthlyProgress: 0.3,
        colorValue: 0xFFF59E0B,
        iconCodePoint: Icons.palette_rounded.codePoint,
        createdAt: DateTime.now(),
      ),
    ];

    for (var p in mockProjects) {
      _repository.addProject(p);
    }
  }

  Future<void> toggleProjectActiveStatus(ProjectModel project) async {
    final updatedProject = ProjectModel(
      id: project.id,
      name: project.name,
      description: project.description,
      clientName: project.clientName,
      hourlyRate: project.hourlyRate,
      currency: project.currency,
      createdAt: project.createdAt,
      isActive: !project.isActive,
      monthlyHours: project.monthlyHours,
      monthlyProgress: project.monthlyProgress,
      colorValue: project.colorValue,
      iconCodePoint: project.iconCodePoint,
      totalHours: project.totalHours,
      totalRevenue: project.totalRevenue,
      weeklyGoalHours: project.weeklyGoalHours,
      thisWeekHours: project.thisWeekHours,
      lastWeekHours: project.lastWeekHours,
      milestoneProgress: project.milestoneProgress,
    );
    try {
      await _repository.updateProject(updatedProject);
    } catch (e) {
      Get.snackbar('Error', 'Failed to update project: $e');
    }
  }

  Future<void> deleteProject(String projectId) async {
    try {
      await _repository.deleteProject(projectId);
      Get.back();
      Get.snackbar('Success', 'Project deleted');
    } catch (e) {
      Get.snackbar('Error', 'Failed to delete project: $e');
    }
  }
}
